Update proto files
Topl/dart_topl_common pull request #3
Opened 2023-07-06 04:50 UTC by berriose

2023-07-06 14:59 UTC, KalervoHyyppa requested changes
I'd make the work easier for clients using this package by parsing ids into list of ints in this package

2023-07-06 14:59 UTC, KalervoHyyppa commented on lib/genus/services/transaction_grpc.dart
> +    required List<int> blockId,
For these requests, it would be easier for the clients of this package to just supply the blockId (which is a string, correct?), and then the package would parse that into a list of ints

2023-07-06 14:59 UTC, KalervoHyyppa commented on lib/genus/services/transaction_grpc.dart
> +    required List<int> transactionId,
Same as above

2023-07-07 06:33 UTC, ultimaterex approved these changes

2023-07-07 17:29 UTC, KalervoHyyppa approved these changes
Awesome

2023-07-07 20:45 UTC, merged